"""Rule-agnostic domain models and validation for the rebuilt prep tool."""

from .models import ArtifactDraftJob, CardGeneration, DisplayMaterial, DisplayMaterialLink, EvidenceStatus, DerivedCard, FactProvenance, RuleProfile, SceneBeat, ScenePlan, SessionLogEntry, SessionState, SourceFact, SourceRef
from .prep import ExtractionWindow, PageSpan, PrepJob, PrepJobCreate, PrepScope, parse_page_spans
from .shadow import (
    ShadowCandidate,
    ShadowCandidateDraft,
    ShadowCandidateEdit,
    ShadowCandidateMergeIn,
    ShadowCandidateSplitIn,
    ShadowResponse,
    ShadowRun,
    ShadowTask,
    ShadowTaskSpec,
)
from .service import (
    DomainValidationError,
    ExampleBundle,
    build_session_review,
    export_cards_markdown,
    export_session_review_markdown,
    load_json,
    load_profile,
    load_profiles,
    draft_scene_plan,
    draft_scene_plan_from_workspace,
    is_handout_fact,
    validate_session,
    validate_bundle,
)

__all__ = [
    "DerivedCard",
    "DisplayMaterial",
    "DisplayMaterialLink",
    "ArtifactDraftJob",
    "CardGeneration",
    "EvidenceStatus",
    "FactProvenance",
    "ExtractionWindow",
    "DomainValidationError",
    "ExampleBundle",
    "PageSpan",
    "PrepJob",
    "PrepJobCreate",
    "PrepScope",
    "RuleProfile",
    "SceneBeat",
    "ScenePlan",
    "SessionLogEntry",
    "SessionState",
    "ShadowCandidate",
    "ShadowCandidateDraft",
    "ShadowCandidateEdit",
    "ShadowCandidateMergeIn",
    "ShadowCandidateSplitIn",
    "ShadowResponse",
    "ShadowRun",
    "ShadowTask",
    "ShadowTaskSpec",
    "SourceFact",
    "SourceRef",
    "build_session_review",
    "export_cards_markdown",
    "export_session_review_markdown",
    "draft_scene_plan",
    "draft_scene_plan_from_workspace",
    "is_handout_fact",
    "load_json",
    "load_profile",
    "load_profiles",
    "parse_page_spans",
    "validate_bundle",
    "validate_session",
]
